import type { Metadata } from "next";
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import { TmdbAuthProvider } from "@/components/tmdb-auth-provider";
import { WatchlistProvider } from "@/components/watchlist-provider";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});


// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-mono", jetbrainsMono.variable)}>
      <body
        className="bg-muted"
      >
        <TmdbAuthProvider>
          <WatchlistProvider>
          <Navbar />
          {children}
          </WatchlistProvider>
        </TmdbAuthProvider>
      </body>
    </html>
  );
}
